#
# Module manifest for module 'ASR-NetworkingAutomation'
#
# Generated by: Azure Infrastructure Team
# Generated on: 12/1/2024
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '12345678-1234-1234-1234-123456789012'

# Author of this module
Author = 'Azure Infrastructure Team'

# Company or vendor of this module
CompanyName = 'Azure Infrastructure Team'

# Copyright statement for this module
Copyright = '(c) 2024 Azure Infrastructure Team. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Azure Site Recovery Networking Automation PowerShell module for automated backup and restoration of VM networking configurations during disaster recovery scenarios. Supports ASG, static IPs, Load Balancer, and Application Gateway configurations.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'Az.Accounts',
    'Az.Network',
    'Az.Compute',
    'Az.Resources',
    'Az.Storage'
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the root module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'Save-NetworkingConfig.ps1',
    'Restore-NetworkingConfig.ps1',
    'ASR-NetworkingAutomation.ps1',
    'README.md',
    'PowerShell-ASR-Networking-Automation-Documentation.md',
    'PowerShell-Quick-Start-Guide.md',
    'ASR-Integration-Guide.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'ASR', 'SiteRecovery', 'Networking', 'DisasterRecovery', 'Automation', 'PowerShell')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.0.0 (December 2024)
- Initial release of Azure Site Recovery Networking Automation module
- Complete networking configuration backup and restoration for VMs
- Support for Application Security Groups (ASG), static IPs, Load Balancer, and Application Gateway configurations
- Azure Automation integration with runbooks
- Cross-region resource mapping for failover scenarios
- Comprehensive logging and monitoring capabilities
- Dry-run mode for testing and validation
- Storage account integration for configuration persistence
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}